In [2]:
import numpy as np
from tabulate import tabulate

from pyfdm import methods
from pyfdm.methods.fuzzy_sets import tfn
from pyfdm import weights as f_weights
from pyfdm import correlations as corrs
from pyfdm.helpers import rank, generate_fuzzy_matrix

import warnings

warnings.filterwarnings('ignore')
np.set_printoptions(suppress=True, precision=3)

# Input data

To perform the multi-criteria evaluation, the decision matrix needs to be defined. It can be determined based on the real data, or created with the method provided in the library.

In [3]:
# real data matrix
real_matrix = np.array([
    [[5, 7, 9], [5, 7, 9], [7, 9, 9]],
    [[1, 3, 5], [3, 5, 7], [3, 5, 7]],
    [[1, 1, 3], [1, 3, 5], [1, 3, 5]],
    [[7, 9, 9], [7, 9, 9], [7, 9, 9]]
])

# randomly generated matrix
# 5 alternatives
# 4 criteria
# lower bound = 5
# upper bound = 10
random_matrix = generate_fuzzy_matrix(5, 4, 5, 10)
print(random_matrix)

[[[8.19  8.552 8.816]
  [5.268 9.057 9.856]
  [6.944 8.37  9.395]
  [7.608 8.032 9.499]]

 [[5.002 6.925 9.764]
  [6.882 7.34  9.824]
  [5.105 7.457 8.621]
  [7.676 8.114 8.702]]

 [[6.38  9.049 9.774]
  [6.096 6.245 9.609]
  [5.489 8.717 9.455]
  [5.011 6.228 7.522]]

 [[6.262 8.489 9.385]
  [5.279 7.527 9.179]
  [5.55  8.511 8.809]
  [6.    8.231 8.874]]

 [[5.074 8.124 8.96 ]
  [5.383 8.917 9.183]
  [6.943 6.978 7.028]
  [8.14  8.307 8.477]]]


# Normalization

Data normalization allows for comparing numbers with each other. It converts the range of values that they fit in range between 0 and 1. Below the usage examples of methods implemented in the library. Types parameter is responsible for the direction of the normalization. One columns' values could be more preferred is the values are lower (`-1`), other one could be more preferred if the values are greater (`1`).

In [4]:
normalizations = {
    'Sum': tfn.normalizations.sum_normalization,
    'Max': tfn.normalizations.max_normalization,
    'Linear': tfn.normalizations.linear_normalization,
    'Minmax': tfn.normalizations.minmax_normalization,
    'Vector': tfn.normalizations.vector_normalization,
    'SAW': tfn.normalizations.saw_normalization
}

types = np.array([1, -1, 1])

for name, norm in normalizations.items():
    nmatrix = norm(real_matrix, types)
    print(f'{name} \n {nmatrix[:2]}')

Sum 
 [[[0.167 0.269 0.5  ]
  [0.354 0.181 0.066]
  [0.269 0.45  0.643]]

 [[0.033 0.115 0.278]
  [0.59  0.254 0.085]
  [0.115 0.25  0.5  ]]]
Max 
 [[[0.714 0.778 1.   ]
  [0.286 0.222 0.   ]
  [1.    1.    1.   ]]

 [[0.143 0.333 0.556]
  [0.571 0.444 0.222]
  [0.429 0.556 0.778]]]
Linear 
 [[[0.556 0.778 1.   ]
  [0.111 0.143 0.2  ]
  [0.778 1.    1.   ]]

 [[0.111 0.333 0.556]
  [0.143 0.2   0.333]
  [0.333 0.556 0.778]]]
Minmax 
 [[[ 0.5   0.75  1.  ]
  [-0.    0.25  0.5 ]
  [ 0.75  1.    1.  ]]

 [[ 0.    0.25  0.5 ]
  [ 0.25  0.5   0.75]
  [ 0.25  0.5   0.75]]]
Vector 
 [[[0.246 0.345 0.443]
  [0.227 0.318 0.409]
  [0.301 0.387 0.387]]

 [[0.049 0.148 0.246]
  [0.136 0.227 0.318]
  [0.129 0.215 0.301]]]
SAW 
 [[[0.556 0.778 1.   ]
  [0.556 0.778 1.   ]
  [0.778 1.    1.   ]]

 [[0.111 0.333 0.556]
  [0.333 0.556 0.778]
  [0.333 0.556 0.778]]]


# Distance

Distance is a measure that allows for indicating how far are two Triangular Fuzzy Numbers from each other. Different techniques have been developed to this end. The measures implemented in the library and their usage are presented below.

In [5]:
distances = {
    'Euclidean': tfn.distances.euclidean_distance,
    'Weighted Euclidean': tfn.distances.weighted_euclidean_distance,
    'Hamming': tfn.distances.hamming_distance,
    'Weighted Hamming': tfn.distances.weighted_hamming_distance,
    'Vertex': tfn.distances.vertex_distance,
    'Tran-Duckstein': tfn.distances.tran_duckstein_distance,
    'L-R': tfn.distances.lr_distance,
    'Mahdavi': tfn.distances.mahdavi_distance
}

x = np.array([2, 4, 5])
y = np.array([1, 2, 3])

for name, distance in distances.items():
    d = distance(x, y)
    print(f'{name}: {d}')

Euclidean: 3.0
Weighted Euclidean: 1.8027756377319946
Hamming: 5
Weighted Hamming: 1.75
Vertex: 1.7320508075688772
Tran-Duckstein: 6.444444444444445
L-R: 15.25
Mahdavi: 1.7795130420052185


# Defuzzification

To create a crisp ranking from the calculations performed in fuzzy environment, the obtained results should be defuzzified. Different techniques can be used to achieve this. The implemented methods and the example of their usage are presented below.

In [6]:
defuzzifications = {
    'Mean': tfn.defuzzifications.mean_defuzzification,
    'Mean Area': tfn.defuzzifications.mean_area_defuzzification,
    'Graded Mean Average': tfn.defuzzifications.graded_mean_average_defuzzification,
    'Weighted Mean': tfn.defuzzifications.weighted_mean_defuzzification                                                                                            
}

x = np.array([0.2, 0.55, 1.1])

for name, defuzzy in defuzzifications.items():
    d = defuzzy(x)
    print(f'{name}: {d}')

Mean: 0.6166666666666667
Mean Area: 0.6000000000000001
Graded Mean Average: 0.5833333333333334
Weighted Mean: 0.6000000000000001


# Weights

Criteria weights in multi-criteria problems are responsible for the importance of each parameter taken into consideration. The greater value assigned to the given criterion, the more important it will be in the assessment. For the purpose of weights definition, 4 methods from the library can be used. They are based on the statistical approach, which makes it possible to define the weights objectively, relying only on data diversity.

In [7]:
weights_methods = {
    'Equal': f_weights.equal_weights,
    'Shannon Entropy' : f_weights.shannon_entropy_weights,
    'STD': f_weights.standard_deviation_weights,
    'Variance': f_weights.variance_weights
}

for name, method in weights_methods.items():
    w = method(random_matrix)
    print(f'{name} \n {w}')

Equal 
 [[0.25 0.25 0.25]
 [0.25 0.25 0.25]
 [0.25 0.25 0.25]
 [0.25 0.25 0.25]]
Shannon Entropy 
 [[0.248 0.262 0.262]
 [0.223 0.244 0.269]
 [0.237 0.252 0.235]
 [0.292 0.242 0.233]]
STD 
 [[0.308 0.222 0.179]
 [0.168 0.327 0.134]
 [0.208 0.208 0.396]
 [0.316 0.243 0.29 ]]
Variance 
 [[0.357 0.191 0.11 ]
 [0.106 0.413 0.062]
 [0.162 0.168 0.539]
 [0.374 0.229 0.289]]


# Evaluation 

Different techniques from the group of Fuzzy Multi-Criteria Decision Analysis methods based on the Triangular Fuzzy Numbers can be used to assess the alternatives. The library contains 10 methods which can be used for this purpose. The examples of their application are presented below.

## Decision matrix

Decision matrix represents the alternatives taken into consideration in the problem. Rows represent amount of alternatives, when columns describes the amount of criteria in the given problem. In the case presented below, we have 4 alternatives and 3 criteria. Moreover, all elements in the matrix should be represent as the Triangular Fuzzy Number.

In [8]:
matrix = np.array([
    [[3, 4, 5],[4, 5, 6],[8, 9, 9]],
    [[6, 7, 8],[4, 5, 6],[1, 2, 3]],
    [[5, 6, 7],[2, 3, 4],[3, 4, 5]],
    [[5, 6, 8],[2, 3, 4],[2, 3, 4]],
    [[7, 8, 9],[7, 8, 9],[5, 6, 7]],
])


## Weights

Weights can be defined objectively, as shown above with the given examples. However, the weights can be also defined directly based on expert knowledge. The library is implemented in a way to handle both crisp and fuzzy weights. Amount of weights should equal the criteria amount. They can be determined as follow.

### Example 1
Crisp weights

In [9]:
crisp_weights = np.array([0.4, 0.4, 0.2])

### Example 2
Triangular Fuzzy Weights

In [10]:
fuzzy_weights = np.array([[5, 7, 9], [7, 9, 9], [3, 5, 7]])


## Criteria 

Criteria types are ment to reflect the direction of the values that is preferable in the problem. If the values for given criterion should be as big as possible, it is then a profit type and represent as `1` in the criteria types array. If the values should be as low as possible, it is then cost and should be represent as `-1` in the array. Moreover, the criteria types amount should equal amount of criteria in the decision matrix.

In [11]:
types = np.array([1, -1, 1])

## fuzzy ARAS

In [12]:
f_aras = methods.fARAS()

Fuzzy ARAS evaluation results with crisp and fuzzy weights  

In [13]:
print(f'Crisp weights: {f_aras(matrix, crisp_weights, types)}')
print(f'Fuzzy weights: {f_aras(matrix, fuzzy_weights, types)}')

Crisp weights: [0.835 0.856 1.114 1.113 0.893]
Fuzzy weights: [0.879 0.834 1.103 1.097 0.896]


We can also use ARAS method with different normalizations. Default, it is a `sum_normalization`.

In [14]:
aras = {
    'Sum': methods.fARAS(tfn.normalizations.sum_normalization),
    'Max': methods.fARAS(tfn.normalizations.max_normalization),
    'Linear': methods.fARAS(tfn.normalizations.linear_normalization),
    'Minmax': methods.fARAS(tfn.normalizations.minmax_normalization),
    'Vector': methods.fARAS(tfn.normalizations.vector_normalization),
    'SAW': methods.fARAS(tfn.normalizations.saw_normalization)
}

For every normalization technique, we can perform assessment to obtain results and check if the type of normalization impacts the outcome.

In [15]:
results = {}
for name, function in aras.items():
    results[name] = function(matrix, fuzzy_weights, types)

In [16]:
print(tabulate([[name, *np.round(pref, 2)] for name, pref in results.items()],
    headers=['Method'] + [f'A{i+1}' for i in range(10)]))

Method      A1    A2    A3    A4    A5
--------  ----  ----  ----  ----  ----
Sum       0.88  0.83  1.1   1.1   0.9
Max       0.98  0.87  1.06  1.04  0.89
Linear    0.84  0.75  0.96  0.95  0.86
Minmax    0.93  0.88  1.08  1.07  0.89
Vector    0.64  0.56  0.48  0.47  0.85
SAW       0.63  0.57  0.49  0.48  0.85


We can see that different preferences are obtained with different normalizations. To check if the alternatives are ranked at the same place despite used normalization method, we can use the method from the library called `rank` which calculates ascending or descending position order based on given array. Since the ARAS method assess better alternatives with higher values, the order should be descending. 

In [17]:
print(tabulate([[name, *rank(pref, descending=True)] for name, pref in results.items()], 
    headers=['Method'] + [f'A{i+1}' for i in range(10)]))

Method      A1    A2    A3    A4    A5
--------  ----  ----  ----  ----  ----
Sum          4     5     1     2     3
Max          3     5     1     2     4
Linear       4     5     1     2     3
Minmax       3     5     1     2     4
Vector       2     3     4     5     1
SAW          2     3     4     5     1


It can be seen, that the ranking of alternatives is different for different normalization techniques. So the user should bear in mind that different methods can have impact the final result obtained within selected evaluation method.

# fuzzy CODAS

In [18]:
f_codas = methods.fCODAS()
print(f_codas(matrix, fuzzy_weights, types))

[  0.3   -27.223  28.96   23.976 -26.013]


Within the CODAS method we can also use different normalizations, as it was in the ARAS method. In addition, we can use different distance metrics to calculate the alternatives preference. Default the `distance_1` is the `euclidean_distance` and `distance_2` is the `hamming_distance`. While calling the fuzzy CODAS object, the `tau` parameter can be given, which is set to `0.02` as default. It is treated as the threshold parameter while calculating the relative assessment matrix. CODAS also assessed better alternatives with higher preferences.

In [19]:
codas = {
    'Pair 1': methods.fCODAS(distance_1=tfn.distances.euclidean_distance, distance_2=tfn.distances.hamming_distance),
    'Pair 2': methods.fCODAS(distance_1=tfn.distances.weighted_euclidean_distance, distance_2=tfn.distances.weighted_hamming_distance),
    'Pair 3': methods.fCODAS(distance_1=tfn.distances.vertex_distance, distance_2=tfn.distances.lr_distance),
    'Pair 4': methods.fCODAS(distance_1=tfn.distances.mahdavi_distance, distance_2=tfn.distances.lr_distance),
    
}

Now, when we defined the CODAS object with different pairs of distances, we can calculate the results.

In [20]:
results = {}
for name, function in codas.items():
    results[name] = function(matrix, fuzzy_weights, types)

In [21]:
print(tabulate([[name, *np.round(pref, 2)] for name, pref in results.items()],
    headers=['Method'] + [f'A{i+1}' for i in range(10)]))

Method       A1       A2      A3      A4       A5
--------  -----  -------  ------  ------  -------
Pair 1     0.3    -27.22   28.96   23.98   -26.01
Pair 2     0.55   -11.46   12.67    9.81   -11.57
Pair 3    15.6   -161.23  148.14  142.27  -144.78
Pair 4    15.8   -157.83  148.41  141.97  -148.34


We can see, that different distance metrics also have impact on the final results.

## fuzzy COPRAS

In [22]:
f_copras = methods.fCOPRAS()
print(f_copras(matrix, fuzzy_weights, types))

[0.804 0.736 0.993 1.    0.824]


As in the case of the ARAS method, in the COPRAS technique, we can also modify the used normalization method. The `saw_normalization` is set as default. Similarly to previous methods, better alternatives are assessed with higher preferences.

In [23]:
copras = {
    'Sum': methods.fCOPRAS(tfn.normalizations.sum_normalization),
    'Max': methods.fCOPRAS(tfn.normalizations.max_normalization),
    'Linear': methods.fCOPRAS(tfn.normalizations.linear_normalization),
    'Minmax': methods.fCOPRAS(tfn.normalizations.minmax_normalization),
    'Vector': methods.fCOPRAS(tfn.normalizations.vector_normalization),
    'SAW': methods.fCOPRAS(tfn.normalizations.saw_normalization)
}

In [24]:
results = {}
for name, function in copras.items():
    results[name] = function(matrix, fuzzy_weights, types)

In [25]:
print(tabulate([[name, *np.round(pref, 2)] for name, pref in results.items()],
    headers=['Method'] + [f'A{i+1}' for i in range(10)]))

Method      A1    A2    A3    A4    A5
--------  ----  ----  ----  ----  ----
Sum       0.7   0.69  0.59  0.61  1
Max       1     0.88  0.92  0.93  0
Linear    0.73  0.67  0.59  0.59  1
Minmax    0.97  0.93  0.94  1     1
Vector    0.81  0.71  1     1     0.79
SAW       0.8   0.74  0.99  1     0.82


## fuzzy EDAS

In [26]:
f_edas = methods.fEDAS()
print(f_edas(matrix, fuzzy_weights, types))

[0.691 0.292 0.698 0.74  0.468]


In case of using the fuzzy EDAS method, we can modify the used defuzzification technique. Default, the fEDAS method has set the defuzzification to the `mean_defuzzification`. EDAS also evaluate better alternatives with higher preferences.

In [27]:
edas = {
    'Mean': methods.fEDAS(defuzzify=tfn.defuzzifications.mean_defuzzification),
    'Mean Area': methods.fEDAS(defuzzify=tfn.defuzzifications.mean_area_defuzzification),
    'Graded Mean Average': methods.fEDAS(defuzzify=tfn.defuzzifications.graded_mean_average_defuzzification),
    'Weighted Mean': methods.fEDAS(defuzzify=tfn.defuzzifications.weighted_mean_defuzzification)                                                                                            
}


After fEDAS object definition, we can calculate the results based on using different defuzzification methods.

In [28]:
results = {}
for name, function in edas.items():
    results[name] = function(matrix, fuzzy_weights, types)

In [29]:
print(tabulate([[name, *np.round(pref, 2)] for name, pref in results.items()],
    headers=['Method'] + [f'A{i+1}' for i in range(10)]))

Method                 A1    A2    A3    A4    A5
-------------------  ----  ----  ----  ----  ----
Mean                 0.69  0.29  0.7   0.74  0.47
Mean Area            0.71  0.3   0.72  0.65  0.45
Graded Mean Average  0.73  0.31  0.75  0.67  0.42
Weighted Mean        0.71  0.3   0.72  0.65  0.45


It can be noticed that the results are highly similar while using different methods to defuzzify fuzzy numbers and obtain crisp values.

## fuzzy MABAC

In [30]:
f_mabac = methods.fMABAC()
print(f_mabac(matrix, fuzzy_weights, types))

[-0.061 -0.644  1.82   1.695 -0.549]


While using the fuzzy MABAC method, the normalization and defuzzification methods can be adjusted. Default, normalization is set to `minmax_normalization` and defuzzify to `mean_defuzzification`. MABAC classify better alternatives with higher preferences

In [31]:
mabac = {
    'Sum': methods.fMABAC(tfn.normalizations.sum_normalization),
    'Max': methods.fMABAC(tfn.normalizations.max_normalization),
    'Linear': methods.fMABAC(tfn.normalizations.linear_normalization),
    'Minmax': methods.fMABAC(tfn.normalizations.minmax_normalization),
    'Vector': methods.fMABAC(tfn.normalizations.vector_normalization),
    'SAW': methods.fMABAC(tfn.normalizations.saw_normalization)
}

In [32]:
results = {}
for name, function in mabac.items():
    results[name] = function(matrix, fuzzy_weights, types)

In [33]:
print(tabulate([[name, *np.round(pref, 2)] for name, pref in results.items()],
    headers=['Method'] + [f'A{i+1}' for i in range(10)]))

Method       A1     A2     A3     A4     A5
--------  -----  -----  -----  -----  -----
Sum       -0.36  -0.52   0.61   0.6   -0.08
Max        0.35  -0.79   1.57   1.34  -0.77
Linear    -0.19  -1.49   1.53   1.31   0.16
Minmax    -0.06  -0.64   1.82   1.7   -0.55
Vector     0.43  -0.31  -0.93  -1.06   2.17
SAW        0.79  -0.5   -2.02  -2.25   5.27


Again we can see, that different techniques used in the assessment have impact on the final result from the fuzzy MCDA method.

## fuzzy MAIRCA

In [34]:
f_mairca = methods.fMAIRCA()
print(f_mairca(matrix, fuzzy_weights, types))

[3.039 3.193 3.315 3.337 2.683]


Fuzzy MAIRCA method allows for adjusting the parameters responsible for the normalization and the distance measures. Default settings covers the `vector_normalization` and the `vertex_distance`. MAIRCA assigns higher preference values to better classified alternatives.

In [35]:
mairca = {
    'Euclidean': methods.fMAIRCA(distance=tfn.distances.euclidean_distance),
    'Weighted Euclidean': methods.fMAIRCA(distance=tfn.distances.weighted_euclidean_distance),
    'Hamming': methods.fMAIRCA(distance=tfn.distances.hamming_distance),
    'Weighted Hamming': methods.fMAIRCA(distance=tfn.distances.weighted_hamming_distance),
    'Vertex': methods.fMAIRCA(distance=tfn.distances.vertex_distance),
    'Tran-Duckstein': methods.fMAIRCA(distance=tfn.distances.tran_duckstein_distance),
    'L-R': methods.fMAIRCA(distance=tfn.distances.lr_distance),
    'Mahdavi': methods.fMAIRCA(distance=tfn.distances.mahdavi_distance)
}


In [36]:
results = {}
for name, function in mairca.items():
    results[name] = function(matrix, fuzzy_weights, types)

In [37]:
print(tabulate([[name, *np.round(pref, 2)] for name, pref in results.items()],
    headers=['Method'] + [f'A{i+1}' for i in range(10)]))

Method                 A1     A2     A3     A4    A5
------------------  -----  -----  -----  -----  ----
Euclidean            5.26   5.53   5.74   5.78  4.65
Weighted Euclidean   3.05   3.21   3.34   3.37  2.7
Hamming              8.96   9.41   9.78   9.85  7.91
Weighted Hamming     3.01   3.17   3.3    3.33  2.67
Vertex               3.04   3.19   3.31   3.34  2.68
Tran-Duckstein       5.53   5.75   6.42   6.52  4.08
L-R                 13.32  13.9   15.49  15.72  9.8
Mahdavi              3.04   3.2    3.32   3.35  2.69


## fuzzy MOORA

In [38]:
f_moora = methods.fMOORA()
print(f_moora(matrix, fuzzy_weights, types))

[1.403 0.707 1.641 1.573 0.931]


Fuzzy MOORA assigns higher preferences to better alternatives. It allows for the modification of the normalization technique, and the default method is set to `vector_normalization`.

In [39]:
moora = {
    'Sum': methods.fMOORA(tfn.normalizations.sum_normalization),
    'Max': methods.fMOORA(tfn.normalizations.max_normalization),
    'Linear': methods.fMOORA(tfn.normalizations.linear_normalization),
    'Minmax': methods.fMOORA(tfn.normalizations.minmax_normalization),
    'Vector': methods.fMOORA(tfn.normalizations.vector_normalization),
    'SAW': methods.fMOORA(tfn.normalizations.saw_normalization)
}

In [40]:
results = {}
for name, function in moora.items():
    results[name] = function(matrix, fuzzy_weights, types)

In [41]:
print(tabulate([[name, *np.round(pref, 2)] for name, pref in results.items()],
    headers=['Method'] + [f'A{i+1}' for i in range(10)]))

Method      A1    A2    A3    A4     A5
--------  ----  ----  ----  ----  -----
Sum       2.36  2.22  2.41  2.54   3.49
Max       6.11  4.88  3.57  3.63  11
Linear    5.18  3.85  1.22  1.23   8.37
Minmax    2.16  1.66  2.03  2.5    8.54
Vector    1.4   0.71  1.64  1.57   0.93
SAW       3.97  2.68  4.74  4.66   3.27


## fuzzy OCRA

In [42]:
f_ocra = methods.fOCRA()
print(f_ocra(matrix, fuzzy_weights, types))

[12.283  0.     9.317  7.306  3.433]


OCRA has one parameter that can be changed during the evaluation. It is the defuzzification method, which default is set to `mean_defuzzification`. OCRA also assess better alternatives with higher preference values.

In [43]:
ocra = {
    'Mean': methods.fOCRA(defuzzify=tfn.defuzzifications.mean_defuzzification),
    'Mean Area': methods.fOCRA(defuzzify=tfn.defuzzifications.mean_area_defuzzification),
    'Graded Mean Average': methods.fOCRA(defuzzify=tfn.defuzzifications.graded_mean_average_defuzzification),
    'Weighted Mean': methods.fOCRA(defuzzify=tfn.defuzzifications.weighted_mean_defuzzification)                                                                                            
}

In [44]:
results = {}
for name, function in ocra.items():
    results[name] = function(matrix, fuzzy_weights, types)

In [45]:
print(tabulate([[name, *np.round(pref, 2)] for name, pref in results.items()],
    headers=['Method'] + [f'A{i+1}' for i in range(10)]))

Method                  A1    A2    A3    A4    A5
-------------------  -----  ----  ----  ----  ----
Mean                 12.28     0  9.32  7.31  3.43
Mean Area            12.28     0  9.3   7.17  3.26
Graded Mean Average  12.27     0  9.28  7.03  3.09
Weighted Mean        12.28     0  9.3   7.17  3.26


## fuzzy TOPSIS

In [46]:
f_topsis = methods.fTOPSIS()
print(f_topsis(matrix, fuzzy_weights, types))

[0.564 0.565 0.552 0.551 0.562]


TOPSIS technique allows for adjusting the parameters responsible for the normalization and the distance calculation. Default methods are set to `linear_normalization` and `vertex_distance`. TOPSIS assures, that better alternatives have higher preferences values. 

In [47]:
topsis = {
    'Sum': methods.fTOPSIS(tfn.normalizations.sum_normalization),
    'Max': methods.fTOPSIS(tfn.normalizations.max_normalization),
    'Linear': methods.fTOPSIS(tfn.normalizations.linear_normalization),
    'Minmax': methods.fTOPSIS(tfn.normalizations.minmax_normalization),
    'Vector': methods.fTOPSIS(tfn.normalizations.vector_normalization),
    'SAW': methods.fTOPSIS(tfn.normalizations.saw_normalization)
}

In [48]:
results = {}
for name, function in topsis.items():
    results[name] = function(matrix, fuzzy_weights, types)

In [49]:
print(tabulate([[name, *np.round(pref, 2)] for name, pref in results.items()],
    headers=['Method'] + [f'A{i+1}' for i in range(10)]))

Method      A1    A2    A3    A4    A5
--------  ----  ----  ----  ----  ----
Sum       0.67  0.61  0.61  0.59  0.64
Max       0.57  0.57  0.56  0.56  0.52
Linear    0.56  0.57  0.55  0.55  0.56
Minmax    0.56  0.55  0.55  0.55  0.56
Vector    0.65  0.62  0.68  0.66  0.61
SAW       0.56  0.56  0.57  0.57  0.54


# fuzzy VIKOR

In [50]:
f_vikor = methods.fVIKOR()
res = f_vikor(matrix, fuzzy_weights, types)
print(f'S: {res[0]}')
print(f'R: {res[1]}')
print(f'Q: {res[2]}')

S: [7.696 8.478 5.966 6.382 8.454]
R: [5.    4.406 3.344 3.781 6.214]
Q: [0.156 0.141 0.003 0.043 0.255]


VIKOR method is characterized by returning three assessment vectors (S, R, Q). The difference between them lays in the way how they are calculated in the final phase of the evaluation. The VIKOR method performance can be adjusted with the defuzzification method, and the default settings for this parameter is `mean_area_defuzzification`. Moreover, while calling the fVIKOR object, the `v` parameter can be given, which translates how the weight of the strategy will behave. It is set to `0.5` as default. VIKOR ranking can be calculated by sorting the preferences in the ascending order, so in the `rank` method, the parameter should be sey as `descending=False`.

In [51]:
vikor = {
    'Mean': methods.fVIKOR(defuzzify=tfn.defuzzifications.mean_defuzzification),
    'Mean Area': methods.fVIKOR(defuzzify=tfn.defuzzifications.mean_area_defuzzification),
    'Graded Mean Average': methods.fVIKOR(defuzzify=tfn.defuzzifications.graded_mean_average_defuzzification),
    'Weighted Mean': methods.fVIKOR(defuzzify=tfn.defuzzifications.weighted_mean_defuzzification)                                                                                            
}

In [52]:
results = {}
for name, function in vikor.items():
    results[name] = function(matrix, fuzzy_weights, types)

In [53]:
print(tabulate([[name, *np.round(pref[0], 2)] for name, pref in results.items()],
    headers=['Method'] + [f'A{i+1}' for i in range(10)]))

Method                 A1    A2    A3    A4    A5
-------------------  ----  ----  ----  ----  ----
Mean                 7.85  8.6   6.13  6.48  8.5
Mean Area            7.7   8.48  5.97  6.38  8.45
Graded Mean Average  7.54  8.36  5.8   6.28  8.4
Weighted Mean        7.7   8.48  5.97  6.38  8.45


# Correlation

Correlation coefficients can be used to indicate the results similarity. They are based on preference or ranking comparison obtained from the multi-criteria assessment. In the library there are available 4 different measures and the example of their usage is presented below. The `pearson_coef` and `spearman_coef` are ment to be used to compare the preference values, while `weighted_spearman_coef` and `ws_rank_similarity_coef` can be used to compare rankings.

### Example 1
Similar preferences

In [54]:
x = np.array([0.69, 0.53, 0.76, 0.81, 0.8])
y = np.array([0.66, 0.54, 0.71, 0.84, 0.77])

print(f'Spearman: {corrs.spearman_coef(x, y)}')
print(f'Pearson: {corrs.pearson_coef(x, y)}')

Spearman: 0.9588593677597358
Pearson: 0.9588593677597358


### Example 2
Different preferences

In [55]:
x = np.array([0.75, 0.39, 0.86, 0.51, 0.63])
y = np.array([0.66, 0.54, 0.71, 0.84, 0.77])

print(f'Spearman: {corrs.spearman_coef(x, y)}')
print(f'Pearson: {corrs.pearson_coef(x, y)}')

Spearman: 0.225511293634533
Pearson: 0.225511293634533


### Example 3
Similar rankings

In [56]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 1, 3, 4, 5])

print(f'Weighted Spearman: {corrs.weighted_spearman_coef(x, y)}')
print(f'WS rank similarity: {corrs.ws_rank_similarity_coef(x, y)}')

Weighted Spearman: 0.85
WS rank similarity: 0.7916666666666667


### Example 4
Different rankings

In [57]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([4, 2, 1, 5, 3])

print(f'Weighted Spearman: {corrs.weighted_spearman_coef(x, y)}')
print(f'WS rank similarity: {corrs.ws_rank_similarity_coef(x, y)}')

Weighted Spearman: 0.050000000000000044
WS rank similarity: 0.46354166666666663
